# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: users.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'users.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0busers.proto\x12\x05users\"\x07\n\x05\x45mpty\"\x19\n\x0bUserRequest\x12\n\n\x02id\x18\x01 \x01(\x05\";\n\x0cUserResponse\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x10\n\x08username\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\"3\n\rUsersResponse\x12\"\n\x05users\x18\x01 \x03(\x0b\x32\x13.users.UserResponse2r\n\x0bUserService\x12\x32\n\x07GetUser\x12\x12.users.UserRequest\x1a\x13.users.UserResponse\x12/\n\tListUsers\x12\x0c.users.Empty\x1a\x14.users.UsersResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'users_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMPTY']._serialized_start=22
  _globals['_EMPTY']._serialized_end=29
  _globals['_USERREQUEST']._serialized_start=31
  _globals['_USERREQUEST']._serialized_end=56
  _globals['_USERRESPONSE']._serialized_start=58
  _globals['_USERRESPONSE']._serialized_end=117
  _globals['_USERSRESPONSE']._serialized_start=119
  _globals['_USERSRESPONSE']._serialized_end=170
  _globals['_USERSERVICE']._serialized_start=172
  _globals['_USERSERVICE']._serialized_end=286
# @@protoc_insertion_point(module_scope)
